#include "NinSnesProfile.h"

#include <array>

namespace {

constexpr NinSnesProfile kUnknownProfile {
    NinSnesProfileId::Unknown,
    NINSNES_UNKNOWN,
    "Unknown",
    NinSnesBaseProfileId::Unknown,
    NinSnesAddressModelId::Direct,
    NinSnesPlaylistModelId::Unknown,
    NinSnesNoteParamModelId::Standard,
    NinSnesProgramResolverId::Direct,
    NinSnesPanModelId::StandardTable,
    NinSnesInstrumentLayoutId::Standard6Byte,
    false,
    false,
    false,
};

constexpr std::array<NinSnesProfile, 17> kProfiles {{
    {NinSnesProfileId::Earlier,
     NINSNES_EARLIER,
     "Earlier",
     NinSnesBaseProfileId::Earlier,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::StandardPercussion,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Earlier5Byte,
     false,
     false,
     false},
    {NinSnesProfileId::Standard,
     NINSNES_STANDARD,
     "Standard",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::StandardPercussion,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     false,
     false,
     false},
    {NinSnesProfileId::Rd1,
     NINSNES_RD1,
     "RD1",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::StandardPercussion,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     false,
     false,
     false},
    {NinSnesProfileId::Rd2,
     NINSNES_RD2,
     "RD2",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::StandardPercussion,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     false,
     false,
     false},
    {NinSnesProfileId::Hal,
     NINSNES_HAL,
     "HAL",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::StandardPercussion,
     NinSnesPanModelId::HalTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     false,
     false,
     false},
    {NinSnesProfileId::Konami,
     NINSNES_KONAMI,
     "Konami",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::KonamiBase,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::StandardPercussion,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::KonamiTuningTable,
     false,
     false,
     false},
    {NinSnesProfileId::Lemmings,
     NINSNES_LEMMINGS,
     "Lemmings",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Lemmings,
     NinSnesProgramResolverId::StandardPercussion,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     false,
     false,
     false},
    {NinSnesProfileId::IntelliFe3,
     NINSNES_INTELLI_FE3,
     "Intelligent Systems FE3",
     NinSnesBaseProfileId::Intelli,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::IntelliTable,
     NinSnesProgramResolverId::Direct,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     true,
     false,
     false},
    {NinSnesProfileId::IntelliTa,
     NINSNES_INTELLI_TA,
     "Intelligent Systems TA",
     NinSnesBaseProfileId::Intelli,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::IntelliTaOverride,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     true,
     true,
     true},
    {NinSnesProfileId::IntelliFe4,
     NINSNES_INTELLI_FE4,
     "Intelligent Systems FE4",
     NinSnesBaseProfileId::Intelli,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::IntelliTable,
     NinSnesProgramResolverId::Direct,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     true,
     false,
     true},
    {NinSnesProfileId::Human,
     NINSNES_HUMAN,
     "Human",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::Direct,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     false,
     false,
     false},
    {NinSnesProfileId::Tose,
     NINSNES_TOSE,
     "TOSE",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Tose,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::StandardPercussion,
     NinSnesPanModelId::ToseLinear,
     NinSnesInstrumentLayoutId::Standard6Byte,
     false,
     false,
     false},
    {NinSnesProfileId::QuintetActR,
     NINSNES_QUINTET_ACTR,
     "Quintet ActRaiser",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::QuintetActRBase,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     false,
     false,
     false},
    {NinSnesProfileId::QuintetActR2,
     NINSNES_QUINTET_ACTR2,
     "Quintet ActRaiser 2",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::QuintetLookup,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     false,
     false,
     false},
    {NinSnesProfileId::QuintetIog,
     NINSNES_QUINTET_IOG,
     "Quintet Illusion of Gaia",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::QuintetLookup,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     false,
     false,
     false},
    {NinSnesProfileId::QuintetTs,
     NINSNES_QUINTET_TS,
     "Quintet Terranigma",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::Direct,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::QuintetLookup,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     false,
     false,
     false},
    {NinSnesProfileId::FalcomYs4,
     NINSNES_FALCOM_YS4,
     "Falcom Ys IV",
     NinSnesBaseProfileId::Standard,
     NinSnesAddressModelId::FalcomBaseOffset,
     NinSnesPlaylistModelId::Standard,
     NinSnesNoteParamModelId::Standard,
     NinSnesProgramResolverId::StandardPercussion,
     NinSnesPanModelId::StandardTable,
     NinSnesInstrumentLayoutId::Standard6Byte,
     false,
     false,
     false},
}};

}  // namespace

const NinSnesProfile& getNinSnesProfile(NinSnesVersion version) {
  for (const auto& profile : kProfiles) {
    if (profile.legacyVersion == version) {
      return profile;
    }
  }

  return kUnknownProfile;
}

NinSnesProfileId getNinSnesProfileId(NinSnesVersion version) {
  return getNinSnesProfile(version).id;
}
