task:
    name: FreeBSD
    freebsd_instance:
        matrix:
            image_family: freebsd-13-2

    install_script: pwd && ls -la && pkg update --force && pkg install -y cmake ninja qt6-base qt6-svg minizip
    compile_script: cmake -B build -GNinja . && cmake --build build --parallel
