/*
 * VGMTrans (c) 2002-2026
 * Licensed under the zlib license,
 * refer to the included LICENSE.txt file
 */

#pragma once

#include "value/base/Source.h"

#include <algorithm>
#include <optional>
#include <span>
#include <string_view>

namespace vgmtrans::core {

[[nodiscard]] inline bool matchesBytes(ByteReader reader, u64 offset, std::string_view bytes) {
  if (!reader.has(offset, bytes.size())) {
    return false;
  }
  for (size_t index = 0; index < bytes.size(); ++index) {
    if (reader.u8At(offset + index) != static_cast<u8>(bytes[index])) {
      return false;
    }
  }
  return true;
}

[[nodiscard]] inline bool matchesBytes(ByteReader reader, u64 offset, std::span<const u8> bytes) {
  if (!reader.has(offset, bytes.size())) {
    return false;
  }
  for (size_t index = 0; index < bytes.size(); ++index) {
    if (reader.u8At(offset + index) != bytes[index]) {
      return false;
    }
  }
  return true;
}

[[nodiscard]] inline std::optional<u32> findBytes(ByteReader reader, std::span<const u8> pattern, u32 begin = 0) {
  if (pattern.empty() || pattern.size() > reader.size() || begin > reader.size() - pattern.size()) {
    return std::nullopt;
  }
  const auto bytes = reader.slice(begin, reader.size() - begin);
  const auto match = std::ranges::search(bytes, pattern);
  return match.begin() == bytes.end()
             ? std::nullopt
             : std::optional<u32>{begin + static_cast<u32>(match.begin() - bytes.begin())};
}

// 'x' bytes are significant; every other mask character is a wildcard.
struct MaskedBytePattern {
  // Arrays are convenient for generated byte lists; string views keep long
  // hand-written signatures readable and preserve embedded zero bytes.
  constexpr MaskedBytePattern(std::span<const u8> bytes, std::string_view mask) : bytes(bytes), mask(mask) {}
  constexpr MaskedBytePattern(std::string_view bytes, std::string_view mask) : textBytes(bytes), mask(mask) {}

  std::span<const u8> bytes;
  std::string_view textBytes;
  std::string_view mask;

  [[nodiscard]] constexpr size_t size() const noexcept { return bytes.empty() ? textBytes.size() : bytes.size(); }
  [[nodiscard]] constexpr u8 at(size_t index) const noexcept {
    return bytes.empty() ? static_cast<u8>(textBytes[index]) : bytes[index];
  }
  [[nodiscard]] bool valid() const noexcept { return size() != 0 && size() == mask.size(); }
  [[nodiscard]] bool matches(std::span<const u8> candidate) const noexcept {
    if (!valid() || candidate.size() < size()) {
      return false;
    }
    for (size_t index = 0; index < size(); ++index) {
      if (mask[index] == 'x' && candidate[index] != at(index)) {
        return false;
      }
    }
    return true;
  }
};

template <size_t ByteCount, size_t MaskCount>
[[nodiscard]] consteval MaskedBytePattern makeMaskedBytePattern(const char (&bytes)[ByteCount],
                                                                const char (&mask)[MaskCount]) {
  static_assert(ByteCount == MaskCount, "byte pattern and mask must have equal lengths");
  return {std::string_view{bytes, ByteCount - 1}, std::string_view{mask, MaskCount - 1}};
}

[[nodiscard]] inline bool matchesBytePattern(ByteReader reader, u64 offset, MaskedBytePattern pattern) {
  if (!pattern.valid() || !reader.has(offset, pattern.size())) {
    return false;
  }
  return pattern.matches(reader.slice(offset, pattern.size()));
}

[[nodiscard]] inline std::optional<u32> findBytePattern(ByteReader reader, MaskedBytePattern pattern, u32 begin = 0) {
  if (!pattern.valid() || pattern.size() > reader.size() || begin > reader.size() - pattern.size()) {
    return std::nullopt;
  }

  const auto bytes = reader.slice(0, reader.size());
  const size_t lastOffset = bytes.size() - pattern.size();
  const size_t anchor = pattern.mask.find('x');
  if (anchor == std::string_view::npos) {
    return begin;
  }

  auto candidate = bytes.begin() + begin + anchor;
  const auto end = bytes.begin() + lastOffset + anchor + 1;
  while ((candidate = std::find(candidate, end, pattern.at(anchor))) != end) {
    const size_t offset = static_cast<size_t>(candidate - bytes.begin()) - anchor;
    if (pattern.matches(bytes.subspan(offset, pattern.size()))) {
      return static_cast<u32>(offset);
    }
    ++candidate;
  }
  return std::nullopt;
}

}  // namespace vgmtrans::core
