/*
 * VGMTrans (c) 2002-2026
 * Licensed under the zlib license,
 * refer to the included LICENSE.txt file
 */

#pragma once

#include "value/base/Source.h"

#include <optional>
#include <span>
#include <string_view>

namespace vgmtrans::core {

[[nodiscard]] inline bool matchesBytes(ByteReader reader, u64 offset, std::string_view bytes) {
  if (!reader.has(offset, bytes.size())) {
    return false;
  }
  for (size_t index = 0; index < bytes.size(); ++index) {
    if (reader.u8At(offset + index) != static_cast<u8>(bytes[index])) {
      return false;
    }
  }
  return true;
}

[[nodiscard]] inline bool matchesBytes(ByteReader reader, u64 offset, std::span<const u8> bytes) {
  if (!reader.has(offset, bytes.size())) {
    return false;
  }
  for (size_t index = 0; index < bytes.size(); ++index) {
    if (reader.u8At(offset + index) != bytes[index]) {
      return false;
    }
  }
  return true;
}

// 'x' bytes are significant; every other mask character is a wildcard.
struct MaskedBytePattern {
  // Arrays are convenient for generated byte lists; string views keep long
  // hand-written signatures readable and preserve embedded zero bytes.
  constexpr MaskedBytePattern(std::span<const u8> bytes, std::string_view mask) : bytes(bytes), mask(mask) {}
  constexpr MaskedBytePattern(std::string_view bytes, std::string_view mask) : textBytes(bytes), mask(mask) {}

  std::span<const u8> bytes;
  std::string_view textBytes;
  std::string_view mask;

  [[nodiscard]] constexpr size_t size() const noexcept { return bytes.empty() ? textBytes.size() : bytes.size(); }
  [[nodiscard]] constexpr u8 at(size_t index) const noexcept {
    return bytes.empty() ? static_cast<u8>(textBytes[index]) : bytes[index];
  }
  [[nodiscard]] bool valid() const noexcept { return size() != 0 && size() == mask.size(); }
};

[[nodiscard]] inline bool matchesBytePattern(ByteReader reader, u64 offset, MaskedBytePattern pattern) {
  if (!pattern.valid() || !reader.has(offset, pattern.size())) {
    return false;
  }
  for (size_t index = 0; index < pattern.size(); ++index) {
    if (pattern.mask[index] == 'x' && reader.u8At(offset + index) != pattern.at(index)) {
      return false;
    }
  }
  return true;
}

[[nodiscard]] inline std::optional<u32> findBytePattern(ByteReader reader, MaskedBytePattern pattern, u32 begin = 0) {
  if (!pattern.valid() || pattern.size() > reader.size() || begin > reader.size() - pattern.size()) {
    return std::nullopt;
  }
  for (u64 offset = begin; offset <= reader.size() - pattern.size(); ++offset) {
    if (matchesBytePattern(reader, offset, pattern)) {
      return static_cast<u32>(offset);
    }
  }
  return std::nullopt;
}

}  // namespace vgmtrans::core
