# Exercise the actual executable, including argument parsing and redirected stdin.
file(MAKE_DIRECTORY "${TEST_DIRECTORY}")
file(WRITE "${TEST_DIRECTORY}/input" "")

function(run_shell expected_status)
  execute_process(COMMAND "${SHELL_EXECUTABLE}" ${ARGN}
    WORKING_DIRECTORY "${TEST_DIRECTORY}"
    INPUT_FILE "${TEST_DIRECTORY}/input"
    OUTPUT_VARIABLE output ERROR_VARIABLE errors RESULT_VARIABLE status TIMEOUT 20)
  if(NOT "${status}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "${ARGN}: expected ${expected_status}, got ${status}\n${output}\n${errors}")
  endif()
  if(output MATCHES "\\(vgmt\\)|VGMTrans shell\\. Type")
    message(FATAL_ERROR "Redirected output must not contain prompts or a welcome banner: ${output}")
  endif()
  set(output "${output}" PARENT_SCOPE)
  set(errors "${errors}" PARENT_SCOPE)
endfunction()

run_shell(0 --help)
if(NOT output MATCHES "Usage: vgmtrans-shell")
  message(FATAL_ERROR "Missing command-line help")
endif()
run_shell(0 -c formats -c "help export")
if(NOT output MATCHES "format: NDS" OR NOT output MATCHES "--loops")
  message(FATAL_ERROR "Repeated -c must run in order with built-in formats registered: ${output}")
endif()
run_shell(1 -c)
run_shell(1 --unknown)
run_shell(1 -c "unknown" -c "help")
if(output MATCHES "Usage:")
  message(FATAL_ERROR "Commands must stop after the first failure")
endif()
run_shell(0 -c quit -c unknown)
run_shell(1 missing.bin -c help)
if(output MATCHES "Usage:")
  message(FATAL_ERROR "Batch commands must not execute after a startup load failure")
endif()

file(WRITE "${TEST_DIRECTORY}/--help" "unrecognized data")
run_shell(1 -- --help)
if(NOT errors MATCHES "no supported music data" OR output MATCHES "Usage:")
  message(FATAL_ERROR "-- must treat following arguments as paths: ${output}\n${errors}")
endif()

file(WRITE "${TEST_DIRECTORY}/input" "formats\r\nhelp export\nquit\nunknown\n")
run_shell(0)
if(NOT output MATCHES "format: NDS" OR NOT output MATCHES "--loops")
  message(FATAL_ERROR "Commands from stdin must run until quit: ${output}")
endif()
file(WRITE "${TEST_DIRECTORY}/input" "unknown\nhelp\n")
run_shell(1)
if(output MATCHES "Usage:")
  message(FATAL_ERROR "Commands from stdin must stop on errors")
endif()
file(WRITE "${TEST_DIRECTORY}/input" "help 'unterminated")
run_shell(1)
if(NOT errors MATCHES "unterminated quote")
  message(FATAL_ERROR "Quote errors should reach stderr: ${errors}")
endif()
file(WRITE "${TEST_DIRECTORY}/input" "help")
run_shell(0)
if(NOT output MATCHES "Usage:")
  message(FATAL_ERROR "The final command should run without a trailing newline")
endif()
