name: "Build / Packaging Issue"
description: "Report build failures or packaging-related issues"
title: "Short description of the issue"
labels: build

body:
  - type: markdown
    id: build_intro_notice
    attributes:
      value: |
        ## Before submitting

        - Read **BUILDING.md** completely and follow it exactly.
        - Build from a recent commit.

  - type: dropdown
    id: issue_type
    attributes:
      label: What type of issue is this?
      multiple: false
      options:
        - Build failure (CMake/configure error)
        - Build failure (compilation/link error)
        - Packaging issue (installer/AppImage/etc.)
        - Not sure
    validations:
      required: true

  - type: textarea
    id: commit_hash
    attributes:
      label: VGMTrans commit being built
      description: Provide the full commit hash.
      placeholder: |
        Example:
        master branch, a1b2c3d4e5f6g7h8i9j0...
    validations:
      required: true

  - type: textarea
    id: cmake_command
    attributes:
      label: Exact CMake command used
      description: Paste the exact command you ran to configure the build.
      placeholder: |
        Example:
        cmake --preset linux-x64
        cmake --build build --parallel
    validations:
      required: false

  - type: textarea
    id: failure_description
    attributes:
      label: Failure details
      description: |
        Describe the failure clearly, providing context.
    validations:
      required: true

  - type: textarea
    id: build_log
    attributes:
      label: Full build output logs
      description: |
        Zip logs and attach them here.
        You can also paste them, but it might be too much data for Github to handle.
        Do NOT paste screenshots.
    validations:
      required: true

  - type: textarea
    id: packaging_details
    attributes:
      label: Packaging details (if applicable)
      description: |
        If this is a packaging issue, specify packaging type (AppImage, installer, etc.),
        how it was produced, what fails (launch error, missing DLL, etc.)
      placeholder: |
        Example:
        AppImage built via CPack.
        Fails at runtime with:
        error while loading shared libraries: ...
    validations:
      required: false

  - type: markdown
    id: build_closing_notice
    attributes:
      value: |
        **Thank you for your time.**
        Issues that do not contain enough information to reproduce the problem may be closed.
