/*
 * VGMTrans (c) 2002-2026
 * Licensed under the zlib license,
 * refer to the included LICENSE.txt file
 */

#include <exception>
#include <iostream>

void runValueRegistryTests();
void runValueCompilerCursorTests();
void runValueCollectionResolverTests();
void runValueSequenceModelTests();
void runValueSequenceVmTests();
void runValueSessionTests();
void runValueSourceMapTests();
void runValueSynthBuilderTests();
void runValueMidiTests();
void runValueSynthExportTests();
void runValuePsxTests();

void capcomSnesLayoutSelectsSongListAndFixedHeaders();
void capcomSnesLayoutFallsBackToV2SongList();
void capcomSnesLayoutReadsOldAndRejectsMalformedDspInit();
void capcomSnesModuleDiscoversSequenceInstrumentsAndSamples();
void capcomSnesModuleWarnsWhenDetectedSynthIsEmpty();
void capcomSnesCompiledAndPerformanceSnapshotsAreStable();
void capcomSnesLfoValuesAreResolvedDuringDecode();
void capcomSnesCompiledCommandsDoNotNeedEngineProfile();
void capcomSnesModuleScansSpcThroughVirtualAramSource();
void capcomSnesInstrumentTableSkipsBlankSlotsLikeLegacy();
void capcomSnesNoteStateCommandsAreTypedAndInterpreted();
void capcomSnesSourceDialectDecodesAndRendersDriverCommands();
void capcomSnesInitialDurationRateIsFullLength();
void capcomSnesPanPerformanceCarriesGainCompensation();
void capcomSnesDialectEmitsSourceOnlyDriverSemantics();
void capcomSnesDialectEmitsStructuredPitchSlides();
void capcomSnesDialectExecutesRepeatUntilCommand();
void capcomSnesDialectAppliesRepeatBreakAttributesOnlyWhenBranchIsTaken();
void capcomSnesDialectDecodesRepeatBreakSideTargets();
void capcomSnesV1DialectPreservesUnknownOneByteEvents();
void konamiSnesLayoutDiscoversDirectHeaderAndSynthTables();
void konamiSnesLayoutInfersSpcDirFromInstrumentTables();
void konamiSnesModuleDiscoversSequenceInstrumentsAndSamples();
void konamiSnesSynthParsersStopAtInvalidBankedInstrument();
void konamiSnesSynthBuilderGroupsPercussionAndPreservesSampleRules();
void konamiSnesProgramChangeReemitsCurrentFineTune();
void konamiSnesEarlyVibratoQuantizesRateAtCommandTempo();
void konamiSnesEchoPreservesGlobalDspState();
void konamiSnesLinearDriverPitchUsesSharedTransitions();
void konamiSnesPercussionUsesPackedGsDrumBank();
void konamiSnesCompilerCursorDecodesVersionedFlowAndTruncation();
void konamiSnesCompilerCursorUsesVersionedOperandLengths();
void konamiSnesEveryVersionRendersSourceFreeCommands();
void konamiSnesSequenceSimulationPreservesDriverVibratoDepth();
void konamiSnesCompiledPlaybackHandlesCallsLoopsTiesAndSlides();
void konamiSnesCompiledAutomationTicksFades();
void konamiSnesPlayOnceCoordinatesGlobalLoopCompletion();
void ninSnesProfilesDescribeEverySupportedDriverFamily();
void ninSnesScannerFindsRequestedSongAcrossSparseTable();
void ninSnesProfilesShareSquaredLevelCurve();
void ninSnesProfilesShareTempoRelativeVibratoClock();
void ninSnesProfilesEmitSubtractiveTremolo();
void ninSnesStandardEchoUsesMaskLevelAndDisable();
void ninSnesKonamiLoopAppliesAndClearsReplayDeltas();
void ninSnesNoteVelocityPreservesLegacyCurve();
void ninSnesIntelligentVoiceTablesUseTypedPlaybackState();
void ninSnesFe3ConditionalJumpUsesCapturedDriverState();
void ninSnesControllerFadesRemainInTheSourceDomain();
void ninSnesPlaylistCarriesTiesAcrossSectionParserResets();
void ninSnesF9UsesSharedPitchTransitions();
void ninSnesPercussionStartsPerNoteVibratoFade();
void ninSnesFixedPercussionBaseIgnoresFaOperand();
void ninSnesEarlierPercussionUsesSeparateSixByteTable();
void ninSnesGainModeInstrumentsUseDspEnvelope();
void mameRomDatabaseAndGroupAssemblyAreValueOriented();
void konamiArcadeModuleBuildsSequencesSynthAndCollections();
void konamiArcadeAdpcmDecoderSupportsForwardAndReverseSamples();
void akaoSnesLayoutDiscoversFf4StyleAram();
void akaoSnesModuleDiscoversSequenceInstrumentsAndSamples();
void akaoSnesV4TieExtendsShortenedPreviousNote();
void akaoSnesCompilerCursorResolvesRelocatedBranchesWithoutRetainingBytes();
void akaoSnesCompilerCursorCoversVersionBoundariesAndDurations();
void akaoSnesCompilerCursorCoversRemapsUnknownsAndTruncation();
void akaoSnesV3VibratoPreservesSquareWaveModesAndSteppedAttack();
void akaoSnesCompiledAutomationTicksControllerAndTempoFades();
void akaoSnesCompilerCursorCoversLoopsAndCpuBranches();
void akaoSnesCompilerCursorCoversNoteModesPitchAndSharedTempo();
void akaoDialectDecodesLegacyRelativeJumpTargets();
void akaoDialectDecodesConditionalBranchSideTargets();
void akaoSequenceAnalysisUsesSemanticOperands();
void akaoTablePointersUseNonControlSourceLinks();
void akaoDialectDecodesRepeatFlowWithoutManualLayerLeaks();
void akaoRepeatSourceLinksUseSpecificRolesOnly();
void akaoVersion10OverlayCommandsUseLegacyLengthsAndProgramChange();
void akaoPanLawFollowsDriverProfile();
void akaoLoopBranchUsesCurrentRepeatPass();
void akaoTieAfterRestDoesNotExtendPreviousNote();
void akaoTempoFadeEmitsDriverTickRamp();
void akaoPitchSlideAppliesOnceToTheNextNote();
void akaoPortamentoRetainsPitchTransitionIntent();
void akaoRequiredArticulationsComeFromInstrumentRows();
void akaoMelodicRegionsDropAdvancingOverlaps();
void akaoSampleSelectionKeepsPreferredAndRequiredCollections();
void akaoScanPublishesStructuralInstrumentSetAndPreparesBoundView();
void ndsLayoutResolvesNamesFilesAndDependencies();
void ndsLayoutBoundsMalformedTablesAndPointers();
void ndsSequenceFatRangesHandleNormalEmptyAndRecoveredFiles();
void ndsModuleOnlyBuildsDependenciesOfReferencedBanks();
void ndsSequenceDialectDecodesAndRendersNoteWaitCommands();
void ndsSequenceDialectComposesPitchBendRangeActions();
void ndsSequenceDialectModelsNitroLfoRegisters();
void ndsSynthModulatorsUseSequenceLfoRanges();
void ndsSequenceDialectRevealsRunningSineLfoAtDepthChange();
void ndsSequenceDialectPreservesPortamentoTimingIntent();
void ndsSequenceDialectPreservesTiedSweepVoices();
void ndsSequenceDialectExecutesCallAndReturn();
void ndsSequenceDialectDiscoversSecondaryTrackAddresses();
void ndsSequenceTrackAddressDiscoveryKeepsMalformedBootstrapCommands();
void ndsSequenceDialectAnnotatesModulationDelayOperands();
void ndsSequenceDialectAnnotatesPartialModulationDelayOperands();
void ndsSequenceDialectKeepsEmptyPlaceholderTrack();
void ndsSequenceDialectMarksUnterminatedVarLenAsTruncated();
void ndsSequenceDialectDoesNotLinkInvalidControlTargets();
void ndsMalformedRecoveryKeepsExecutableJumps();
void ndsSynthParserPreservesInfiniteRelease();
void ndsSynthParserDerivesAdpcmLengthsSafely();
void ndsWaveArchiveReportsTruncatedSampleHeaders();
void ndsSynthBuilderPreservesSparseWaveIndexesAcrossArchives();

int main() {
  try {
    runValueRegistryTests();
    runValueCompilerCursorTests();
    runValueCollectionResolverTests();
    runValueSequenceModelTests();
    runValueSequenceVmTests();
    runValueSessionTests();
    runValueSourceMapTests();
    runValueSynthBuilderTests();
    runValueMidiTests();
    runValueSynthExportTests();
    runValuePsxTests();

    capcomSnesLayoutSelectsSongListAndFixedHeaders();
    capcomSnesLayoutFallsBackToV2SongList();
    capcomSnesLayoutReadsOldAndRejectsMalformedDspInit();
    capcomSnesModuleDiscoversSequenceInstrumentsAndSamples();
    capcomSnesModuleWarnsWhenDetectedSynthIsEmpty();
    capcomSnesCompiledAndPerformanceSnapshotsAreStable();
    capcomSnesLfoValuesAreResolvedDuringDecode();
    capcomSnesCompiledCommandsDoNotNeedEngineProfile();
    capcomSnesModuleScansSpcThroughVirtualAramSource();
    capcomSnesInstrumentTableSkipsBlankSlotsLikeLegacy();
    capcomSnesNoteStateCommandsAreTypedAndInterpreted();
    capcomSnesSourceDialectDecodesAndRendersDriverCommands();
    capcomSnesInitialDurationRateIsFullLength();
    capcomSnesPanPerformanceCarriesGainCompensation();
    capcomSnesDialectEmitsSourceOnlyDriverSemantics();
    capcomSnesDialectEmitsStructuredPitchSlides();
    capcomSnesDialectExecutesRepeatUntilCommand();
    capcomSnesDialectAppliesRepeatBreakAttributesOnlyWhenBranchIsTaken();
    capcomSnesDialectDecodesRepeatBreakSideTargets();
    capcomSnesV1DialectPreservesUnknownOneByteEvents();
    konamiSnesLayoutDiscoversDirectHeaderAndSynthTables();
    konamiSnesLayoutInfersSpcDirFromInstrumentTables();
    konamiSnesModuleDiscoversSequenceInstrumentsAndSamples();
    konamiSnesSynthParsersStopAtInvalidBankedInstrument();
    konamiSnesSynthBuilderGroupsPercussionAndPreservesSampleRules();
    konamiSnesProgramChangeReemitsCurrentFineTune();
    konamiSnesEarlyVibratoQuantizesRateAtCommandTempo();
    konamiSnesEchoPreservesGlobalDspState();
    konamiSnesLinearDriverPitchUsesSharedTransitions();
    konamiSnesPercussionUsesPackedGsDrumBank();
    konamiSnesCompilerCursorDecodesVersionedFlowAndTruncation();
    konamiSnesCompilerCursorUsesVersionedOperandLengths();
    konamiSnesEveryVersionRendersSourceFreeCommands();
    konamiSnesSequenceSimulationPreservesDriverVibratoDepth();
    konamiSnesCompiledPlaybackHandlesCallsLoopsTiesAndSlides();
    konamiSnesCompiledAutomationTicksFades();
    konamiSnesPlayOnceCoordinatesGlobalLoopCompletion();
    ninSnesProfilesDescribeEverySupportedDriverFamily();
    ninSnesScannerFindsRequestedSongAcrossSparseTable();
    ninSnesProfilesShareSquaredLevelCurve();
    ninSnesProfilesShareTempoRelativeVibratoClock();
    ninSnesProfilesEmitSubtractiveTremolo();
    ninSnesStandardEchoUsesMaskLevelAndDisable();
    ninSnesKonamiLoopAppliesAndClearsReplayDeltas();
    ninSnesNoteVelocityPreservesLegacyCurve();
    ninSnesIntelligentVoiceTablesUseTypedPlaybackState();
    ninSnesFe3ConditionalJumpUsesCapturedDriverState();
    ninSnesControllerFadesRemainInTheSourceDomain();
    ninSnesPlaylistCarriesTiesAcrossSectionParserResets();
    ninSnesF9UsesSharedPitchTransitions();
    ninSnesPercussionStartsPerNoteVibratoFade();
    ninSnesFixedPercussionBaseIgnoresFaOperand();
    ninSnesEarlierPercussionUsesSeparateSixByteTable();
    ninSnesGainModeInstrumentsUseDspEnvelope();
    mameRomDatabaseAndGroupAssemblyAreValueOriented();
    konamiArcadeModuleBuildsSequencesSynthAndCollections();
    konamiArcadeAdpcmDecoderSupportsForwardAndReverseSamples();
    akaoSnesLayoutDiscoversFf4StyleAram();
    akaoSnesModuleDiscoversSequenceInstrumentsAndSamples();
    akaoSnesV4TieExtendsShortenedPreviousNote();
    akaoSnesCompilerCursorResolvesRelocatedBranchesWithoutRetainingBytes();
    akaoSnesCompilerCursorCoversVersionBoundariesAndDurations();
    akaoSnesCompilerCursorCoversRemapsUnknownsAndTruncation();
    akaoSnesV3VibratoPreservesSquareWaveModesAndSteppedAttack();
    akaoSnesCompiledAutomationTicksControllerAndTempoFades();
    akaoSnesCompilerCursorCoversLoopsAndCpuBranches();
    akaoSnesCompilerCursorCoversNoteModesPitchAndSharedTempo();
    akaoDialectDecodesLegacyRelativeJumpTargets();
    akaoDialectDecodesConditionalBranchSideTargets();
    akaoSequenceAnalysisUsesSemanticOperands();
    akaoTablePointersUseNonControlSourceLinks();
    akaoDialectDecodesRepeatFlowWithoutManualLayerLeaks();
    akaoRepeatSourceLinksUseSpecificRolesOnly();
    akaoVersion10OverlayCommandsUseLegacyLengthsAndProgramChange();
    akaoPanLawFollowsDriverProfile();
    akaoLoopBranchUsesCurrentRepeatPass();
    akaoTieAfterRestDoesNotExtendPreviousNote();
    akaoTempoFadeEmitsDriverTickRamp();
    akaoPitchSlideAppliesOnceToTheNextNote();
    akaoPortamentoRetainsPitchTransitionIntent();
    akaoRequiredArticulationsComeFromInstrumentRows();
    akaoMelodicRegionsDropAdvancingOverlaps();
    akaoSampleSelectionKeepsPreferredAndRequiredCollections();
    akaoScanPublishesStructuralInstrumentSetAndPreparesBoundView();
    ndsLayoutResolvesNamesFilesAndDependencies();
    ndsLayoutBoundsMalformedTablesAndPointers();
    ndsSequenceFatRangesHandleNormalEmptyAndRecoveredFiles();
    ndsModuleOnlyBuildsDependenciesOfReferencedBanks();
    ndsSequenceDialectDecodesAndRendersNoteWaitCommands();
    ndsSequenceDialectComposesPitchBendRangeActions();
    ndsSequenceDialectModelsNitroLfoRegisters();
    ndsSynthModulatorsUseSequenceLfoRanges();
    ndsSequenceDialectRevealsRunningSineLfoAtDepthChange();
    ndsSequenceDialectPreservesPortamentoTimingIntent();
    ndsSequenceDialectPreservesTiedSweepVoices();
    ndsSequenceDialectExecutesCallAndReturn();
    ndsSequenceDialectDiscoversSecondaryTrackAddresses();
    ndsSequenceTrackAddressDiscoveryKeepsMalformedBootstrapCommands();
    ndsSequenceDialectAnnotatesModulationDelayOperands();
    ndsSequenceDialectAnnotatesPartialModulationDelayOperands();
    ndsSequenceDialectKeepsEmptyPlaceholderTrack();
    ndsSequenceDialectMarksUnterminatedVarLenAsTruncated();
    ndsSequenceDialectDoesNotLinkInvalidControlTargets();
    ndsMalformedRecoveryKeepsExecutableJumps();
    ndsSynthParserPreservesInfiniteRelease();
    ndsSynthParserDerivesAdpcmLengthsSafely();
    ndsWaveArchiveReportsTruncatedSampleHeaders();
    ndsSynthBuilderPreservesSparseWaveIndexesAcrossArchives();
  } catch (const std::exception& ex) {
    std::cerr << ex.what() << '\n';
    return 1;
  }

  return 0;
}
