/*
 * VGMTrans (c) 2002-2026
 * Licensed under the zlib license,
 * refer to the included LICENSE.txt file
 */

#include <exception>
#include <iostream>

void runValueRegistryTests();
void runValueCompilerCursorTests();
void runValueCollectionDiscoveryTests();
void runValueCollectionStitchTests();
void runValueInstrumentVariantTests();
void runValueSequenceModelTests();
void runValueSequenceVmTests();
void runValueSessionTests();
void runValueSourceMapTests();
void runSampleFilteringTests();
void runValueSynthBuilderTests();
void runValueMidiTests();
void runValueSynthExportTests();
void runValuePsxTests();
void sonyPs1SequenceSupportsBothLoopCountGenerations();
void sonyPs1TempoBytesPreserveSourceOrder();
void sonyPs1SepAndVabLayoutsAreVersionAware();
void sonyPs1ModuleBuildsCombinedAndSplitVabSynths();
void runSonyPs1CollectionBindingTests();
void suzukiPs1DynamicAdsrUsesAuditedDriverCommands();
void suzukiPs1ModuleBuildsFractionallyTunedWdsSynth();
void runTriAcePs1ModuleTests();
void hosaSequencePreservesAuditedGrammarAndMixer();
void hosaVibratoUsesExactDriverTables();
void hosaUnterminatedFinalTrackStopsAtZeroPadding();
void hosaTracksMayShareSequenceData();
void hosaSequenceLoopRestoresEveryTrack();
void hosaModuleBuildsDriverAccurateRegions();
void runSuzukiSnesModuleTests();
void runFalcomSnesModuleTests();
void runGraphResSnesModuleTests();
void runHeartBeatSnesModuleTests();
void runHeartBeatPs1ModuleTests();
void runKonamiPs1ModuleTests();
void runAsciiShuichiSnesModuleTests();
void runPrismSnesModuleTests();
void runHudsonSnesModuleTests();
void runItikitiSnesModuleTests();
void runMoriSnesModuleTests();
void runSoftCreatSnesModuleTests();
void runCompileSnesModuleTests();
void runWolfTeamSnesModuleTests();
void runMp2kModuleTests();
void runNamcoSnesModuleTests();
void runNeverlandSnesModuleTests();
void runPandoraBoxSnesModuleTests();

void capcomSnesLayoutSelectsSongListAndFixedHeaders();
void capcomSnesLayoutFallsBackToV2SongList();
void capcomSnesLayoutReadsOldAndRejectsMalformedDspInit();
void capcomSnesModuleDiscoversSequenceInstrumentsAndSamples();
void capcomSnesModuleWarnsWhenDetectedSynthIsEmpty();
void capcomSnesCompiledAndPerformanceSnapshotsAreStable();
void capcomSnesLfoValuesAreResolvedDuringDecode();
void capcomSnesCompiledCommandsDoNotNeedEngineProfile();
void capcomSnesModuleScansSpcThroughVirtualAramSource();
void capcomSnesInstrumentTableSkipsBlankSlotsLikeLegacy();
void capcomSnesNoteStateCommandsAreTypedAndInterpreted();
void capcomSnesSourceDecoderDecodesAndRendersDriverCommands();
void capcomSnesInitialDurationRateIsFullLength();
void capcomSnesPanPerformanceCarriesGainCompensation();
void capcomSnesSequenceEmitsSourceOnlyDriverSemantics();
void capcomSnesReleaseRateIsStickyAcrossInstrumentChanges();
void capcomSnesSequenceEmitsStructuredPitchSlides();
void capcomSnesSequenceExecutesRepeatUntilCommand();
void capcomSnesSequenceAppliesRepeatBreakAttributesOnlyWhenBranchIsTaken();
void capcomSnesSequenceDecodesRepeatBreakSideTargets();
void capcomSnesV1SequencePreservesUnknownOneByteEvents();
void konamiSnesLayoutDiscoversDirectHeaderAndSynthTables();
void konamiSnesLayoutInfersSpcDirFromInstrumentTables();
void konamiSnesBatmanReturnsAramUsesV2LayoutAndBoundedBank();
void konamiSnesModuleDiscoversSequenceInstrumentsAndSamples();
void konamiSnesSynthParsersStopAtInvalidBankedInstrument();
void konamiSnesSynthBuilderGroupsPercussionAndPreservesSampleRules();
void konamiSnesProgramChangeReemitsCurrentFineTune();
void konamiSnesEarlyVibratoQuantizesRateAtCommandTempo();
void konamiSnesEchoPreservesGlobalDspState();
void konamiSnesLinearDriverPitchUsesSharedTransitions();
void konamiSnesProportionalPortamentoMatchesDriverCurve();
void konamiSnesPercussionUsesPackedGsDrumBank();
void konamiSnesCompilerCursorDecodesVersionedFlowAndTruncation();
void konamiSnesCompilerCursorUsesVersionedOperandLengths();
void konamiSnesDynamicAdsrMatchesEachDriverFamily();
void konamiSnesPreservesLateEnvelopeRegisterState();
void konamiSnesMixerAndPanFollowVersionedDriverMath();
void konamiSnesZeroNotesAndLegatoMatchDriverGating();
void konamiSnesLowCommandsAndInstrumentPanAreVersioned();
void konamiSnesEveryVersionRendersSourceFreeCommands();
void konamiSnesSequenceSimulationPreservesDriverVibratoDepth();
void konamiSnesCompiledPlaybackHandlesCallsLoopsTiesAndSlides();
void konamiSnesHeldNoteUsesRealizedInlineSlidePitch();
void konamiSnesHeldNoteRestartsPitchEnvelopeWithoutRetrigger();
void konamiSnesCompiledAutomationTicksFades();
void konamiSnesPlayOnceCoordinatesGlobalLoopCompletion();
void ninSnesProfilesDescribeEverySupportedDriverFamily();
void ninSnesKonamiClockControlsTempo();
void ninSnesScannerFindsRequestedSongAcrossSparseTable();
void ninSnesKoeiUsesSixBgmTracksAndPendingRequest();
void ninSnesProfilesShareSquaredLevelCurve();
void ninSnesProfilesShareTempoRelativeVibratoClock();
void ninSnesProfilesEmitSubtractiveTremolo();
void ninSnesStandardEchoUsesMaskLevelAndDisable();
void ninSnesKonamiLoopAppliesAndClearsReplayDeltas();
void ninSnesKonamiAdsrGainEmitsNeutralEnvelopeState();
void ninSnesNoteVelocityPreservesLegacyCurve();
void ninSnesIntelligentVoiceTablesUseTypedPlaybackState();
void ninSnesProgramResolutionIsCapturedByRuntime();
void ninSnesFe3ConditionalJumpUsesCapturedDriverState();
void ninSnesControllerFadesRemainInTheSourceDomain();
void ninSnesPrepassClearsMasterVolumeAutomationBinding();
void ninSnesPlaylistCarriesTiesAcrossSectionParserResets();
void ninSnesKonamiZeroDurationRateContinuesHeldVoice();
void ninSnesF9UsesSharedPitchTransitions();
void ninSnesPercussionStartsPerNoteVibratoFade();
void ninSnesFixedPercussionBaseIgnoresFaOperand();
void ninSnesKonamiPercussionUsesDriverMapAndNeutralTuning();
void ninSnesEarlierPercussionUsesSeparateSixByteTable();
void ninSnesGainModeInstrumentsUseDspEnvelope();
void ninSnesIdentityMappedSilentSlotsAreSparse();
void rareSnesLayoutsDifferentiateDriverFamilies();
void rareSnesProfilesDecodeTheirDistinctOpcodeTails();
void rareSnesSignedStereoVolumesPreserveDriverRelativeLevels();
void rareSnesPhysicalLfosAndPitchEnvelopesUseTimerClock();
void rareSnesPitchEnvelopeInvertsOnlyItsInitialSteps();
void rareSnesCallsConditionalBranchesAndLongDurationsExecuteSourceFree();
void mameRomDatabaseAndGroupAssemblyAreValueOriented();
void konamiArcadeModuleBuildsSequencesSynthAndCollections();
void konamiArcadeGxLfosMatchDriverState();
void konamiArcadeGxDriverQuirksRemainRepresented();
void konamiArcadeExpressionPersistsThroughSoftwareRelease();
void konamiArcadeZeroReleaseUsesHardwareVoiceLifetime();
void konamiArcadeTempoSlidesAreCanceledAcrossTracks();
void konamiArcadeMysticDrumPitchSlidesUseTablePitch();
void konamiArcadeAdpcmDecoderSupportsForwardAndReverseSamples();
void konamiTmnt2ContextualFlowAndDynamicYmReleaseRender();
void konamiTmnt2DialectWidthsMatchTheMusicParsers();
void konamiTmnt2SampleReleaseTremoloAndAdpcmAreDistinct();
void konamiTmnt2SteppedModulationRunsAndRestoresOverTime();
void konamiTmnt2NativeLfoUsesHardwareRateAndChannelRamp();
void konamiTmnt2AliasesMiscSamplesAndTrackLabels();
void cps3MameDecryptionUsesDriverAddressMask();
void kabukiMameDecryptionUsesDataAddressPath();
void cps1ModuleRetainsYm2151AndOkiDomains();
void cps1V1DefaultsAndPitchWrappingMatchLegacyDriver();
void cps2EarlyModuleUsesPhysicalModulation();
void cps2ShortEnvelopeIncludesItsCompletionTick();
void cps2EarlyZeroRateSlursRemainLinked();
void cps2EarlyPortamentoStartsOnFirstTiedNote();
void cps2LateDriverSemanticsRemainProfileSpecific();
void cps3ModuleDecodesDelayPrefixesLegatoAndRegions();
void cps3HeldNotesRetargetOneVoiceWithoutLosingPitch();
void cpsLateRepeatBreakUsesEndOfCommandBase();
void cps3TerminalMaxRepeatActsAsPracticalLoop();
void cpsLateControlFlowOffsetsFollowEachDriver();
void akaoSnesLayoutDiscoversFf4StyleAram();
void akaoSnesLayoutDiscoversLatePercussionTable();
void akaoSnesModuleDiscoversSequenceInstrumentsAndSamples();
void akaoSnesV4TieExtendsShortenedPreviousNote();
void akaoSnesCompilerCursorResolvesRelocatedBranchesWithoutRetainingBytes();
void akaoSnesCompilerCursorCoversVersionBoundariesAndDurations();
void akaoSnesDynamicAdsrCoversHardwareFields();
void akaoSnesV1SoftwareEnvelopesDriveLevelWithoutDynamicInstruments();
void akaoSnesCompilerCursorCoversRemapsUnknownsAndTruncation();
void akaoSnesV3VibratoPreservesSquareWaveModesAndSteppedAttack();
void akaoSnesV4LfosPreserveDriverFamiliesAndPackedModes();
void akaoSnesCompiledAutomationTicksControllerAndTempoFades();
void akaoSnesCompilerCursorCoversLoopsAndCpuBranches();
void akaoSnesCompilerCursorCoversNoteModesPitchAndSharedTempo();
void akaoSnesSecretOfManaEchoEventsEmitReverb();
void akaoSequenceLayoutRejectsFalsePositiveHeaders();
void akaoSequenceDecodesLegacyRelativeJumpTargets();
void akaoSequenceDecodesConditionalBranchSideTargets();
void akaoSequenceAnalysisUsesSemanticOperands();
void akaoTablePointersUseNonControlSourceLinks();
void akaoSequenceDecodesRepeatFlowWithoutManualLayerLeaks();
void akaoRepeatSourceLinksUseSpecificRolesOnly();
void akaoVersion10OverlayCommandsUseLegacyLengthsAndProgramChange();
void akaoPanLawFollowsDriverProfile();
void akaoLoopBranchUsesCurrentRepeatPass();
void akaoTieAfterRestDoesNotExtendPreviousNote();
void akaoTempoFadeEmitsDriverTickRamp();
void akaoPitchSlideAppliesOnceToTheNextNote();
void akaoPortamentoRetainsPitchTransitionIntent();
void akaoRequiredArticulationsComeFromInstrumentRows();
void akaoMelodicRegionsDropAdvancingOverlaps();
void akaoSampleSelectionKeepsPreferredAndRequiredCollections();
void akaoCollectionPrefersCompleteSamplesFromSequenceSource();
void akaoScanPublishesStructuralInstrumentSetAndBindsCollectionView();
void ndsLayoutResolvesNamesFilesAndDependencies();
void ndsLayoutBoundsMalformedTablesAndPointers();
void ndsSequenceFatRangesHandleNormalEmptyAndRecoveredFiles();
void ndsModuleOnlyBuildsDependenciesOfReferencedBanks();
void ndsSequenceDecodesAndRendersNoteWaitCommands();
void ndsSequenceComposesPitchBendRangeBehavior();
void ndsSequenceEmitsStickyDynamicAdsr();
void ndsSequenceModelsNitroLfoRegisters();
void ndsSynthModulatorsUseSequenceLfoRanges();
void ndsSequenceRevealsRunningSineLfoAtDepthChange();
void ndsSequencePreservesPortamentoTimingIntent();
void ndsSequencePreservesTiedSweepVoices();
void ndsSequenceExecutesCallAndReturn();
void ndsSequenceDiscoversSecondaryTrackAddresses();
void ndsSequenceTrackAddressDiscoveryKeepsMalformedBootstrapCommands();
void ndsSequenceAnnotatesModulationDelayOperands();
void ndsSequenceAnnotatesPartialModulationDelayOperands();
void ndsSequenceKeepsEmptyPlaceholderTrack();
void ndsSequenceMarksUnterminatedVarLenAsTruncated();
void ndsSequenceDoesNotLinkInvalidControlTargets();
void ndsMalformedRecoveryKeepsExecutableJumps();
void ndsSynthParserConvertsMaximumReleaseRate();
void ndsSynthParserDerivesAdpcmLengthsSafely();
void ndsWaveArchiveReportsTruncatedSampleHeaders();
void ndsSynthBuilderPreservesSparseWaveIndexesAcrossArchives();
void segSatVlCurveMatchesMm8Saturation();
void segSatTempoDeltaBytesPreserveSourceOrder();
void segSatCollectionBindingSuppliesVlTablesToSequence();
void segSatRuntimeMapSelectsBankInsideAnotherSampleSpan();
void segSatMultiBankPlaybackUsesTheActiveBanksVlTable();
void segSatCollectionBindingUsesRetainedVelocityBanksFromSeparateSources();
void segSatSsfExtractorUsesFourByteMiniHeader();

int main() {
  try {
    runValueRegistryTests();
    runValueCompilerCursorTests();
    runValueCollectionDiscoveryTests();
    runValueCollectionStitchTests();
    runValueInstrumentVariantTests();
    runValueSequenceModelTests();
    runValueSequenceVmTests();
    runValueSessionTests();
    runValueSourceMapTests();
    runSampleFilteringTests();
    runValueSynthBuilderTests();
    runValueMidiTests();
    runValueSynthExportTests();
    runValuePsxTests();
    sonyPs1SequenceSupportsBothLoopCountGenerations();
    sonyPs1TempoBytesPreserveSourceOrder();
    sonyPs1SepAndVabLayoutsAreVersionAware();
    sonyPs1ModuleBuildsCombinedAndSplitVabSynths();
    runSonyPs1CollectionBindingTests();
    runSuzukiSnesModuleTests();
    runFalcomSnesModuleTests();
    runGraphResSnesModuleTests();
    runHeartBeatSnesModuleTests();
    runAsciiShuichiSnesModuleTests();
    runHudsonSnesModuleTests();
    runItikitiSnesModuleTests();
    runMoriSnesModuleTests();
    runSoftCreatSnesModuleTests();
    runNeverlandSnesModuleTests();
    runPandoraBoxSnesModuleTests();
    runCompileSnesModuleTests();
    runPrismSnesModuleTests();

    capcomSnesLayoutSelectsSongListAndFixedHeaders();
    capcomSnesLayoutFallsBackToV2SongList();
    capcomSnesLayoutReadsOldAndRejectsMalformedDspInit();
    capcomSnesModuleDiscoversSequenceInstrumentsAndSamples();
    capcomSnesModuleWarnsWhenDetectedSynthIsEmpty();
    capcomSnesCompiledAndPerformanceSnapshotsAreStable();
    capcomSnesLfoValuesAreResolvedDuringDecode();
    capcomSnesCompiledCommandsDoNotNeedEngineProfile();
    capcomSnesModuleScansSpcThroughVirtualAramSource();
    capcomSnesInstrumentTableSkipsBlankSlotsLikeLegacy();
    capcomSnesNoteStateCommandsAreTypedAndInterpreted();
    capcomSnesSourceDecoderDecodesAndRendersDriverCommands();
    capcomSnesInitialDurationRateIsFullLength();
    capcomSnesPanPerformanceCarriesGainCompensation();
    capcomSnesSequenceEmitsSourceOnlyDriverSemantics();
    capcomSnesReleaseRateIsStickyAcrossInstrumentChanges();
    capcomSnesSequenceEmitsStructuredPitchSlides();
    capcomSnesSequenceExecutesRepeatUntilCommand();
    capcomSnesSequenceAppliesRepeatBreakAttributesOnlyWhenBranchIsTaken();
    capcomSnesSequenceDecodesRepeatBreakSideTargets();
    capcomSnesV1SequencePreservesUnknownOneByteEvents();
    konamiSnesLayoutDiscoversDirectHeaderAndSynthTables();
    konamiSnesLayoutInfersSpcDirFromInstrumentTables();
    konamiSnesBatmanReturnsAramUsesV2LayoutAndBoundedBank();
    konamiSnesModuleDiscoversSequenceInstrumentsAndSamples();
    konamiSnesSynthParsersStopAtInvalidBankedInstrument();
    konamiSnesSynthBuilderGroupsPercussionAndPreservesSampleRules();
    konamiSnesProgramChangeReemitsCurrentFineTune();
    konamiSnesEarlyVibratoQuantizesRateAtCommandTempo();
    konamiSnesEchoPreservesGlobalDspState();
    konamiSnesLinearDriverPitchUsesSharedTransitions();
    konamiSnesProportionalPortamentoMatchesDriverCurve();
    konamiSnesPercussionUsesPackedGsDrumBank();
    konamiSnesCompilerCursorDecodesVersionedFlowAndTruncation();
    konamiSnesCompilerCursorUsesVersionedOperandLengths();
    konamiSnesDynamicAdsrMatchesEachDriverFamily();
    konamiSnesPreservesLateEnvelopeRegisterState();
    konamiSnesMixerAndPanFollowVersionedDriverMath();
    konamiSnesZeroNotesAndLegatoMatchDriverGating();
    konamiSnesLowCommandsAndInstrumentPanAreVersioned();
    konamiSnesEveryVersionRendersSourceFreeCommands();
    konamiSnesSequenceSimulationPreservesDriverVibratoDepth();
    konamiSnesCompiledPlaybackHandlesCallsLoopsTiesAndSlides();
    konamiSnesHeldNoteUsesRealizedInlineSlidePitch();
    konamiSnesHeldNoteRestartsPitchEnvelopeWithoutRetrigger();
    konamiSnesCompiledAutomationTicksFades();
    konamiSnesPlayOnceCoordinatesGlobalLoopCompletion();
    ninSnesProfilesDescribeEverySupportedDriverFamily();
    ninSnesKonamiClockControlsTempo();
    ninSnesScannerFindsRequestedSongAcrossSparseTable();
    ninSnesKoeiUsesSixBgmTracksAndPendingRequest();
    ninSnesProfilesShareSquaredLevelCurve();
    ninSnesProfilesShareTempoRelativeVibratoClock();
    ninSnesProfilesEmitSubtractiveTremolo();
    ninSnesStandardEchoUsesMaskLevelAndDisable();
    ninSnesKonamiLoopAppliesAndClearsReplayDeltas();
    ninSnesKonamiAdsrGainEmitsNeutralEnvelopeState();
    ninSnesNoteVelocityPreservesLegacyCurve();
    ninSnesIntelligentVoiceTablesUseTypedPlaybackState();
    ninSnesProgramResolutionIsCapturedByRuntime();
    ninSnesFe3ConditionalJumpUsesCapturedDriverState();
    ninSnesControllerFadesRemainInTheSourceDomain();
    ninSnesPrepassClearsMasterVolumeAutomationBinding();
    ninSnesPlaylistCarriesTiesAcrossSectionParserResets();
    ninSnesKonamiZeroDurationRateContinuesHeldVoice();
    ninSnesF9UsesSharedPitchTransitions();
    ninSnesPercussionStartsPerNoteVibratoFade();
    ninSnesFixedPercussionBaseIgnoresFaOperand();
    ninSnesKonamiPercussionUsesDriverMapAndNeutralTuning();
    ninSnesEarlierPercussionUsesSeparateSixByteTable();
    ninSnesGainModeInstrumentsUseDspEnvelope();
    ninSnesIdentityMappedSilentSlotsAreSparse();
    rareSnesLayoutsDifferentiateDriverFamilies();
    rareSnesProfilesDecodeTheirDistinctOpcodeTails();
    rareSnesSignedStereoVolumesPreserveDriverRelativeLevels();
    rareSnesPhysicalLfosAndPitchEnvelopesUseTimerClock();
    rareSnesPitchEnvelopeInvertsOnlyItsInitialSteps();
    rareSnesCallsConditionalBranchesAndLongDurationsExecuteSourceFree();
    mameRomDatabaseAndGroupAssemblyAreValueOriented();
    konamiArcadeModuleBuildsSequencesSynthAndCollections();
    konamiArcadeGxLfosMatchDriverState();
    konamiArcadeGxDriverQuirksRemainRepresented();
    konamiArcadeExpressionPersistsThroughSoftwareRelease();
    konamiArcadeZeroReleaseUsesHardwareVoiceLifetime();
    konamiArcadeTempoSlidesAreCanceledAcrossTracks();
    konamiArcadeMysticDrumPitchSlidesUseTablePitch();
    konamiArcadeAdpcmDecoderSupportsForwardAndReverseSamples();
    konamiTmnt2ContextualFlowAndDynamicYmReleaseRender();
    konamiTmnt2DialectWidthsMatchTheMusicParsers();
    konamiTmnt2SampleReleaseTremoloAndAdpcmAreDistinct();
    konamiTmnt2SteppedModulationRunsAndRestoresOverTime();
    konamiTmnt2NativeLfoUsesHardwareRateAndChannelRamp();
    konamiTmnt2AliasesMiscSamplesAndTrackLabels();
    cps3MameDecryptionUsesDriverAddressMask();
    kabukiMameDecryptionUsesDataAddressPath();
    cps1ModuleRetainsYm2151AndOkiDomains();
    cps1V1DefaultsAndPitchWrappingMatchLegacyDriver();
    cps2EarlyModuleUsesPhysicalModulation();
    cps2ShortEnvelopeIncludesItsCompletionTick();
    cps2EarlyZeroRateSlursRemainLinked();
    cps2EarlyPortamentoStartsOnFirstTiedNote();
    cps2LateDriverSemanticsRemainProfileSpecific();
    cps3ModuleDecodesDelayPrefixesLegatoAndRegions();
    cps3HeldNotesRetargetOneVoiceWithoutLosingPitch();
    cpsLateRepeatBreakUsesEndOfCommandBase();
    cps3TerminalMaxRepeatActsAsPracticalLoop();
    cpsLateControlFlowOffsetsFollowEachDriver();
    akaoSnesLayoutDiscoversFf4StyleAram();
    akaoSnesLayoutDiscoversLatePercussionTable();
    akaoSnesModuleDiscoversSequenceInstrumentsAndSamples();
    akaoSnesV4TieExtendsShortenedPreviousNote();
    akaoSnesCompilerCursorResolvesRelocatedBranchesWithoutRetainingBytes();
    akaoSnesCompilerCursorCoversVersionBoundariesAndDurations();
    akaoSnesDynamicAdsrCoversHardwareFields();
    akaoSnesV1SoftwareEnvelopesDriveLevelWithoutDynamicInstruments();
    akaoSnesCompilerCursorCoversRemapsUnknownsAndTruncation();
    akaoSnesV3VibratoPreservesSquareWaveModesAndSteppedAttack();
    akaoSnesV4LfosPreserveDriverFamiliesAndPackedModes();
    akaoSnesCompiledAutomationTicksControllerAndTempoFades();
    akaoSnesCompilerCursorCoversLoopsAndCpuBranches();
    akaoSnesCompilerCursorCoversNoteModesPitchAndSharedTempo();
    akaoSnesSecretOfManaEchoEventsEmitReverb();
    akaoSequenceLayoutRejectsFalsePositiveHeaders();
    akaoSequenceDecodesLegacyRelativeJumpTargets();
    akaoSequenceDecodesConditionalBranchSideTargets();
    akaoSequenceAnalysisUsesSemanticOperands();
    akaoTablePointersUseNonControlSourceLinks();
    akaoSequenceDecodesRepeatFlowWithoutManualLayerLeaks();
    akaoRepeatSourceLinksUseSpecificRolesOnly();
    akaoVersion10OverlayCommandsUseLegacyLengthsAndProgramChange();
    akaoPanLawFollowsDriverProfile();
    akaoLoopBranchUsesCurrentRepeatPass();
    akaoTieAfterRestDoesNotExtendPreviousNote();
    akaoTempoFadeEmitsDriverTickRamp();
    akaoPitchSlideAppliesOnceToTheNextNote();
    akaoPortamentoRetainsPitchTransitionIntent();
    akaoRequiredArticulationsComeFromInstrumentRows();
    akaoMelodicRegionsDropAdvancingOverlaps();
    akaoSampleSelectionKeepsPreferredAndRequiredCollections();
    akaoCollectionPrefersCompleteSamplesFromSequenceSource();
    akaoScanPublishesStructuralInstrumentSetAndBindsCollectionView();
    runMp2kModuleTests();
    runNamcoSnesModuleTests();
    ndsLayoutResolvesNamesFilesAndDependencies();
    ndsLayoutBoundsMalformedTablesAndPointers();
    ndsSequenceFatRangesHandleNormalEmptyAndRecoveredFiles();
    ndsModuleOnlyBuildsDependenciesOfReferencedBanks();
    ndsSequenceDecodesAndRendersNoteWaitCommands();
    ndsSequenceComposesPitchBendRangeBehavior();
    ndsSequenceEmitsStickyDynamicAdsr();
    ndsSequenceModelsNitroLfoRegisters();
    ndsSynthModulatorsUseSequenceLfoRanges();
    ndsSequenceRevealsRunningSineLfoAtDepthChange();
    ndsSequencePreservesPortamentoTimingIntent();
    ndsSequencePreservesTiedSweepVoices();
    ndsSequenceExecutesCallAndReturn();
    ndsSequenceDiscoversSecondaryTrackAddresses();
    ndsSequenceTrackAddressDiscoveryKeepsMalformedBootstrapCommands();
    ndsSequenceAnnotatesModulationDelayOperands();
    ndsSequenceAnnotatesPartialModulationDelayOperands();
    ndsSequenceKeepsEmptyPlaceholderTrack();
    ndsSequenceMarksUnterminatedVarLenAsTruncated();
    ndsSequenceDoesNotLinkInvalidControlTargets();
    ndsMalformedRecoveryKeepsExecutableJumps();
    ndsSynthParserConvertsMaximumReleaseRate();
    ndsSynthParserDerivesAdpcmLengthsSafely();
    ndsWaveArchiveReportsTruncatedSampleHeaders();
    ndsSynthBuilderPreservesSparseWaveIndexesAcrossArchives();
    segSatVlCurveMatchesMm8Saturation();
    segSatTempoDeltaBytesPreserveSourceOrder();
    segSatCollectionBindingSuppliesVlTablesToSequence();
    segSatRuntimeMapSelectsBankInsideAnotherSampleSpan();
    segSatMultiBankPlaybackUsesTheActiveBanksVlTable();
    segSatCollectionBindingUsesRetainedVelocityBanksFromSeparateSources();
    segSatSsfExtractorUsesFourByteMiniHeader();
    suzukiPs1DynamicAdsrUsesAuditedDriverCommands();
    suzukiPs1ModuleBuildsFractionallyTunedWdsSynth();
    runHeartBeatPs1ModuleTests();
    runKonamiPs1ModuleTests();
    runTriAcePs1ModuleTests();
    hosaSequencePreservesAuditedGrammarAndMixer();
    hosaVibratoUsesExactDriverTables();
    hosaUnterminatedFinalTrackStopsAtZeroPadding();
    hosaTracksMayShareSequenceData();
    hosaSequenceLoopRestoresEveryTrack();
    hosaModuleBuildsDriverAccurateRegions();
    runWolfTeamSnesModuleTests();
  } catch (const std::exception& ex) {
    std::cerr << ex.what() << '\n';
    return 1;
  }

  return 0;
}
