/*
 * VGMTrans (c) 2002-2026
 * Licensed under the zlib license,
 * refer to the included LICENSE.txt file
 */

#include <exception>
#include <iostream>

void runValueRegistryTests();
void runValueCompilerCursorTests();
void runValueCollectionResolverTests();
void runValueDynamicEnvelopeTests();
void runValueSequenceModelTests();
void runValueSequenceVmTests();
void runValueSessionTests();
void runValueSourceMapTests();
void runSampleFilteringTests();
void runValueSynthBuilderTests();
void runValueMidiTests();
void runValueSynthExportTests();
void runValuePsxTests();
void suzukiPs1DynamicAdsrUsesAuditedDriverCommands();
void suzukiPs1ModuleBuildsFractionallyTunedWdsSynth();
void runSuzukiSnesModuleTests();
void runWolfTeamSnesModuleTests();

void capcomSnesLayoutSelectsSongListAndFixedHeaders();
void capcomSnesLayoutFallsBackToV2SongList();
void capcomSnesLayoutReadsOldAndRejectsMalformedDspInit();
void capcomSnesModuleDiscoversSequenceInstrumentsAndSamples();
void capcomSnesModuleWarnsWhenDetectedSynthIsEmpty();
void capcomSnesCompiledAndPerformanceSnapshotsAreStable();
void capcomSnesLfoValuesAreResolvedDuringDecode();
void capcomSnesCompiledCommandsDoNotNeedEngineProfile();
void capcomSnesModuleScansSpcThroughVirtualAramSource();
void capcomSnesInstrumentTableSkipsBlankSlotsLikeLegacy();
void capcomSnesNoteStateCommandsAreTypedAndInterpreted();
void capcomSnesSourceDialectDecodesAndRendersDriverCommands();
void capcomSnesInitialDurationRateIsFullLength();
void capcomSnesPanPerformanceCarriesGainCompensation();
void capcomSnesDialectEmitsSourceOnlyDriverSemantics();
void capcomSnesReleaseRateIsStickyAcrossInstrumentChanges();
void capcomSnesDialectEmitsStructuredPitchSlides();
void capcomSnesDialectExecutesRepeatUntilCommand();
void capcomSnesDialectAppliesRepeatBreakAttributesOnlyWhenBranchIsTaken();
void capcomSnesDialectDecodesRepeatBreakSideTargets();
void capcomSnesV1DialectPreservesUnknownOneByteEvents();
void konamiSnesLayoutDiscoversDirectHeaderAndSynthTables();
void konamiSnesLayoutInfersSpcDirFromInstrumentTables();
void konamiSnesBatmanReturnsAramUsesV2LayoutAndBoundedBank();
void konamiSnesModuleDiscoversSequenceInstrumentsAndSamples();
void konamiSnesSynthParsersStopAtInvalidBankedInstrument();
void konamiSnesSynthBuilderGroupsPercussionAndPreservesSampleRules();
void konamiSnesProgramChangeReemitsCurrentFineTune();
void konamiSnesEarlyVibratoQuantizesRateAtCommandTempo();
void konamiSnesEchoPreservesGlobalDspState();
void konamiSnesLinearDriverPitchUsesSharedTransitions();
void konamiSnesProportionalPortamentoMatchesDriverCurve();
void konamiSnesPercussionUsesPackedGsDrumBank();
void konamiSnesCompilerCursorDecodesVersionedFlowAndTruncation();
void konamiSnesCompilerCursorUsesVersionedOperandLengths();
void konamiSnesDynamicAdsrMatchesEachDriverFamily();
void konamiSnesPreservesLateEnvelopeRegisterState();
void konamiSnesMixerAndPanFollowVersionedDriverMath();
void konamiSnesZeroNotesAndLegatoMatchDriverGating();
void konamiSnesLowCommandsAndInstrumentPanAreVersioned();
void konamiSnesEveryVersionRendersSourceFreeCommands();
void konamiSnesSequenceSimulationPreservesDriverVibratoDepth();
void konamiSnesCompiledPlaybackHandlesCallsLoopsTiesAndSlides();
void konamiSnesHeldNoteUsesRealizedInlineSlidePitch();
void konamiSnesHeldNoteRestartsPitchEnvelopeWithoutRetrigger();
void konamiSnesCompiledAutomationTicksFades();
void konamiSnesPlayOnceCoordinatesGlobalLoopCompletion();
void ninSnesProfilesDescribeEverySupportedDriverFamily();
void ninSnesKonamiClockControlsTempo();
void ninSnesScannerFindsRequestedSongAcrossSparseTable();
void ninSnesProfilesShareSquaredLevelCurve();
void ninSnesProfilesShareTempoRelativeVibratoClock();
void ninSnesProfilesEmitSubtractiveTremolo();
void ninSnesStandardEchoUsesMaskLevelAndDisable();
void ninSnesKonamiLoopAppliesAndClearsReplayDeltas();
void ninSnesKonamiAdsrGainEmitsNeutralEnvelopeState();
void ninSnesNoteVelocityPreservesLegacyCurve();
void ninSnesIntelligentVoiceTablesUseTypedPlaybackState();
void ninSnesFe3ConditionalJumpUsesCapturedDriverState();
void ninSnesControllerFadesRemainInTheSourceDomain();
void ninSnesPrepassClearsMasterVolumeAutomationBinding();
void ninSnesPlaylistCarriesTiesAcrossSectionParserResets();
void ninSnesKonamiZeroDurationRateContinuesHeldVoice();
void ninSnesF9UsesSharedPitchTransitions();
void ninSnesPercussionStartsPerNoteVibratoFade();
void ninSnesFixedPercussionBaseIgnoresFaOperand();
void ninSnesKonamiPercussionUsesDriverMapAndNeutralTuning();
void ninSnesEarlierPercussionUsesSeparateSixByteTable();
void ninSnesGainModeInstrumentsUseDspEnvelope();
void ninSnesIdentityMappedSilentSlotsAreSparse();
void rareSnesLayoutsDifferentiateDriverFamilies();
void rareSnesProfilesDecodeTheirDistinctOpcodeTails();
void rareSnesSignedStereoVolumesPreserveDriverRelativeLevels();
void rareSnesPhysicalLfosAndPitchEnvelopesUseTimerClock();
void rareSnesPitchEnvelopeInvertsOnlyItsInitialSteps();
void rareSnesCallsConditionalBranchesAndLongDurationsExecuteSourceFree();
void mameRomDatabaseAndGroupAssemblyAreValueOriented();
void konamiArcadeModuleBuildsSequencesSynthAndCollections();
void konamiArcadeGxLfosMatchDriverState();
void konamiArcadeGxDriverQuirksRemainRepresented();
void konamiArcadeExpressionPersistsThroughSoftwareRelease();
void konamiArcadeZeroReleaseUsesHardwareVoiceLifetime();
void konamiArcadeTempoSlidesAreCanceledAcrossTracks();
void konamiArcadeMysticDrumPitchSlidesUseTablePitch();
void konamiArcadeAdpcmDecoderSupportsForwardAndReverseSamples();
void cps3MameDecryptionUsesDriverAddressMask();
void kabukiMameDecryptionUsesDataAddressPath();
void cps1ModuleRetainsYm2151AndOkiDomains();
void cps1V1DefaultsAndPitchWrappingMatchLegacyDriver();
void cps2EarlyModuleUsesPhysicalModulation();
void cps2ShortEnvelopeIncludesItsCompletionTick();
void cps2EarlyZeroRateSlursRemainLinked();
void cps2EarlyPortamentoStartsOnFirstTiedNote();
void cps2LateDriverSemanticsRemainProfileSpecific();
void cps3ModuleDecodesDelayPrefixesLegatoAndRegions();
void cps3HeldNotesRetargetOneVoiceWithoutLosingPitch();
void cpsLateRepeatBreakUsesEndOfCommandBase();
void cps3TerminalMaxRepeatActsAsPracticalLoop();
void cpsLateControlFlowOffsetsFollowEachDriver();
void akaoSnesLayoutDiscoversFf4StyleAram();
void akaoSnesLayoutDiscoversLatePercussionTable();
void akaoSnesModuleDiscoversSequenceInstrumentsAndSamples();
void akaoSnesV4TieExtendsShortenedPreviousNote();
void akaoSnesCompilerCursorResolvesRelocatedBranchesWithoutRetainingBytes();
void akaoSnesCompilerCursorCoversVersionBoundariesAndDurations();
void akaoSnesDynamicAdsrCoversHardwareFields();
void akaoSnesV1SoftwareEnvelopesDriveLevelWithoutDynamicInstruments();
void akaoSnesCompilerCursorCoversRemapsUnknownsAndTruncation();
void akaoSnesV3VibratoPreservesSquareWaveModesAndSteppedAttack();
void akaoSnesV4LfosPreserveDriverFamiliesAndPackedModes();
void akaoSnesCompiledAutomationTicksControllerAndTempoFades();
void akaoSnesCompilerCursorCoversLoopsAndCpuBranches();
void akaoSnesCompilerCursorCoversNoteModesPitchAndSharedTempo();
void akaoSnesSecretOfManaEchoEventsEmitReverb();
void akaoDialectDecodesLegacyRelativeJumpTargets();
void akaoDialectDecodesConditionalBranchSideTargets();
void akaoSequenceAnalysisUsesSemanticOperands();
void akaoTablePointersUseNonControlSourceLinks();
void akaoDialectDecodesRepeatFlowWithoutManualLayerLeaks();
void akaoRepeatSourceLinksUseSpecificRolesOnly();
void akaoVersion10OverlayCommandsUseLegacyLengthsAndProgramChange();
void akaoPanLawFollowsDriverProfile();
void akaoLoopBranchUsesCurrentRepeatPass();
void akaoTieAfterRestDoesNotExtendPreviousNote();
void akaoTempoFadeEmitsDriverTickRamp();
void akaoPitchSlideAppliesOnceToTheNextNote();
void akaoPortamentoRetainsPitchTransitionIntent();
void akaoRequiredArticulationsComeFromInstrumentRows();
void akaoMelodicRegionsDropAdvancingOverlaps();
void akaoSampleSelectionKeepsPreferredAndRequiredCollections();
void akaoScanPublishesStructuralInstrumentSetAndPreparesBoundView();
void ndsLayoutResolvesNamesFilesAndDependencies();
void ndsLayoutBoundsMalformedTablesAndPointers();
void ndsSequenceFatRangesHandleNormalEmptyAndRecoveredFiles();
void ndsModuleOnlyBuildsDependenciesOfReferencedBanks();
void ndsSequenceDialectDecodesAndRendersNoteWaitCommands();
void ndsSequenceDialectComposesPitchBendRangeActions();
void ndsSequenceDialectEmitsStickyDynamicAdsr();
void ndsSequenceDialectModelsNitroLfoRegisters();
void ndsSynthModulatorsUseSequenceLfoRanges();
void ndsSequenceDialectRevealsRunningSineLfoAtDepthChange();
void ndsSequenceDialectPreservesPortamentoTimingIntent();
void ndsSequenceDialectPreservesTiedSweepVoices();
void ndsSequenceDialectExecutesCallAndReturn();
void ndsSequenceDialectDiscoversSecondaryTrackAddresses();
void ndsSequenceTrackAddressDiscoveryKeepsMalformedBootstrapCommands();
void ndsSequenceDialectAnnotatesModulationDelayOperands();
void ndsSequenceDialectAnnotatesPartialModulationDelayOperands();
void ndsSequenceDialectKeepsEmptyPlaceholderTrack();
void ndsSequenceDialectMarksUnterminatedVarLenAsTruncated();
void ndsSequenceDialectDoesNotLinkInvalidControlTargets();
void ndsMalformedRecoveryKeepsExecutableJumps();
void ndsSynthParserConvertsMaximumReleaseRate();
void ndsSynthParserDerivesAdpcmLengthsSafely();
void ndsWaveArchiveReportsTruncatedSampleHeaders();
void ndsSynthBuilderPreservesSparseWaveIndexesAcrossArchives();
void segSatVlCurveMatchesMm8Saturation();
void segSatCollectionPreparationSuppliesVlTablesToSequence();
void segSatRuntimeMapSelectsBankInsideAnotherSampleSpan();
void segSatMultiBankPlaybackUsesTheActiveBanksVlTable();
void segSatCollectionPreparationReadsVelocityBanksFromSeparateSources();
void segSatSsfExtractorUsesFourByteMiniHeader();

int main() {
  try {
    runValueRegistryTests();
    runValueCompilerCursorTests();
    runValueCollectionResolverTests();
    runValueDynamicEnvelopeTests();
    runValueSequenceModelTests();
    runValueSequenceVmTests();
    runValueSessionTests();
    runValueSourceMapTests();
    runSampleFilteringTests();
    runValueSynthBuilderTests();
    runValueMidiTests();
    runValueSynthExportTests();
    runValuePsxTests();
    runSuzukiSnesModuleTests();

    capcomSnesLayoutSelectsSongListAndFixedHeaders();
    capcomSnesLayoutFallsBackToV2SongList();
    capcomSnesLayoutReadsOldAndRejectsMalformedDspInit();
    capcomSnesModuleDiscoversSequenceInstrumentsAndSamples();
    capcomSnesModuleWarnsWhenDetectedSynthIsEmpty();
    capcomSnesCompiledAndPerformanceSnapshotsAreStable();
    capcomSnesLfoValuesAreResolvedDuringDecode();
    capcomSnesCompiledCommandsDoNotNeedEngineProfile();
    capcomSnesModuleScansSpcThroughVirtualAramSource();
    capcomSnesInstrumentTableSkipsBlankSlotsLikeLegacy();
    capcomSnesNoteStateCommandsAreTypedAndInterpreted();
    capcomSnesSourceDialectDecodesAndRendersDriverCommands();
    capcomSnesInitialDurationRateIsFullLength();
    capcomSnesPanPerformanceCarriesGainCompensation();
    capcomSnesDialectEmitsSourceOnlyDriverSemantics();
    capcomSnesReleaseRateIsStickyAcrossInstrumentChanges();
    capcomSnesDialectEmitsStructuredPitchSlides();
    capcomSnesDialectExecutesRepeatUntilCommand();
    capcomSnesDialectAppliesRepeatBreakAttributesOnlyWhenBranchIsTaken();
    capcomSnesDialectDecodesRepeatBreakSideTargets();
    capcomSnesV1DialectPreservesUnknownOneByteEvents();
    konamiSnesLayoutDiscoversDirectHeaderAndSynthTables();
    konamiSnesLayoutInfersSpcDirFromInstrumentTables();
    konamiSnesBatmanReturnsAramUsesV2LayoutAndBoundedBank();
    konamiSnesModuleDiscoversSequenceInstrumentsAndSamples();
    konamiSnesSynthParsersStopAtInvalidBankedInstrument();
    konamiSnesSynthBuilderGroupsPercussionAndPreservesSampleRules();
    konamiSnesProgramChangeReemitsCurrentFineTune();
    konamiSnesEarlyVibratoQuantizesRateAtCommandTempo();
    konamiSnesEchoPreservesGlobalDspState();
    konamiSnesLinearDriverPitchUsesSharedTransitions();
    konamiSnesProportionalPortamentoMatchesDriverCurve();
    konamiSnesPercussionUsesPackedGsDrumBank();
    konamiSnesCompilerCursorDecodesVersionedFlowAndTruncation();
    konamiSnesCompilerCursorUsesVersionedOperandLengths();
    konamiSnesDynamicAdsrMatchesEachDriverFamily();
    konamiSnesPreservesLateEnvelopeRegisterState();
    konamiSnesMixerAndPanFollowVersionedDriverMath();
    konamiSnesZeroNotesAndLegatoMatchDriverGating();
    konamiSnesLowCommandsAndInstrumentPanAreVersioned();
    konamiSnesEveryVersionRendersSourceFreeCommands();
    konamiSnesSequenceSimulationPreservesDriverVibratoDepth();
    konamiSnesCompiledPlaybackHandlesCallsLoopsTiesAndSlides();
    konamiSnesHeldNoteUsesRealizedInlineSlidePitch();
    konamiSnesHeldNoteRestartsPitchEnvelopeWithoutRetrigger();
    konamiSnesCompiledAutomationTicksFades();
    konamiSnesPlayOnceCoordinatesGlobalLoopCompletion();
    ninSnesProfilesDescribeEverySupportedDriverFamily();
    ninSnesKonamiClockControlsTempo();
    ninSnesScannerFindsRequestedSongAcrossSparseTable();
    ninSnesProfilesShareSquaredLevelCurve();
    ninSnesProfilesShareTempoRelativeVibratoClock();
    ninSnesProfilesEmitSubtractiveTremolo();
    ninSnesStandardEchoUsesMaskLevelAndDisable();
    ninSnesKonamiLoopAppliesAndClearsReplayDeltas();
    ninSnesKonamiAdsrGainEmitsNeutralEnvelopeState();
    ninSnesNoteVelocityPreservesLegacyCurve();
    ninSnesIntelligentVoiceTablesUseTypedPlaybackState();
    ninSnesFe3ConditionalJumpUsesCapturedDriverState();
    ninSnesControllerFadesRemainInTheSourceDomain();
    ninSnesPrepassClearsMasterVolumeAutomationBinding();
    ninSnesPlaylistCarriesTiesAcrossSectionParserResets();
    ninSnesKonamiZeroDurationRateContinuesHeldVoice();
    ninSnesF9UsesSharedPitchTransitions();
    ninSnesPercussionStartsPerNoteVibratoFade();
    ninSnesFixedPercussionBaseIgnoresFaOperand();
    ninSnesKonamiPercussionUsesDriverMapAndNeutralTuning();
    ninSnesEarlierPercussionUsesSeparateSixByteTable();
    ninSnesGainModeInstrumentsUseDspEnvelope();
    ninSnesIdentityMappedSilentSlotsAreSparse();
    rareSnesLayoutsDifferentiateDriverFamilies();
    rareSnesProfilesDecodeTheirDistinctOpcodeTails();
    rareSnesSignedStereoVolumesPreserveDriverRelativeLevels();
    rareSnesPhysicalLfosAndPitchEnvelopesUseTimerClock();
    rareSnesPitchEnvelopeInvertsOnlyItsInitialSteps();
    rareSnesCallsConditionalBranchesAndLongDurationsExecuteSourceFree();
    mameRomDatabaseAndGroupAssemblyAreValueOriented();
    konamiArcadeModuleBuildsSequencesSynthAndCollections();
    konamiArcadeGxLfosMatchDriverState();
    konamiArcadeGxDriverQuirksRemainRepresented();
    konamiArcadeExpressionPersistsThroughSoftwareRelease();
    konamiArcadeZeroReleaseUsesHardwareVoiceLifetime();
    konamiArcadeTempoSlidesAreCanceledAcrossTracks();
    konamiArcadeMysticDrumPitchSlidesUseTablePitch();
    konamiArcadeAdpcmDecoderSupportsForwardAndReverseSamples();
    cps3MameDecryptionUsesDriverAddressMask();
    kabukiMameDecryptionUsesDataAddressPath();
    cps1ModuleRetainsYm2151AndOkiDomains();
    cps1V1DefaultsAndPitchWrappingMatchLegacyDriver();
    cps2EarlyModuleUsesPhysicalModulation();
    cps2ShortEnvelopeIncludesItsCompletionTick();
    cps2EarlyZeroRateSlursRemainLinked();
    cps2EarlyPortamentoStartsOnFirstTiedNote();
    cps2LateDriverSemanticsRemainProfileSpecific();
    cps3ModuleDecodesDelayPrefixesLegatoAndRegions();
    cps3HeldNotesRetargetOneVoiceWithoutLosingPitch();
    cpsLateRepeatBreakUsesEndOfCommandBase();
    cps3TerminalMaxRepeatActsAsPracticalLoop();
    cpsLateControlFlowOffsetsFollowEachDriver();
    akaoSnesLayoutDiscoversFf4StyleAram();
    akaoSnesLayoutDiscoversLatePercussionTable();
    akaoSnesModuleDiscoversSequenceInstrumentsAndSamples();
    akaoSnesV4TieExtendsShortenedPreviousNote();
    akaoSnesCompilerCursorResolvesRelocatedBranchesWithoutRetainingBytes();
    akaoSnesCompilerCursorCoversVersionBoundariesAndDurations();
    akaoSnesDynamicAdsrCoversHardwareFields();
    akaoSnesV1SoftwareEnvelopesDriveLevelWithoutDynamicInstruments();
    akaoSnesCompilerCursorCoversRemapsUnknownsAndTruncation();
    akaoSnesV3VibratoPreservesSquareWaveModesAndSteppedAttack();
    akaoSnesV4LfosPreserveDriverFamiliesAndPackedModes();
    akaoSnesCompiledAutomationTicksControllerAndTempoFades();
    akaoSnesCompilerCursorCoversLoopsAndCpuBranches();
    akaoSnesCompilerCursorCoversNoteModesPitchAndSharedTempo();
    akaoSnesSecretOfManaEchoEventsEmitReverb();
    akaoDialectDecodesLegacyRelativeJumpTargets();
    akaoDialectDecodesConditionalBranchSideTargets();
    akaoSequenceAnalysisUsesSemanticOperands();
    akaoTablePointersUseNonControlSourceLinks();
    akaoDialectDecodesRepeatFlowWithoutManualLayerLeaks();
    akaoRepeatSourceLinksUseSpecificRolesOnly();
    akaoVersion10OverlayCommandsUseLegacyLengthsAndProgramChange();
    akaoPanLawFollowsDriverProfile();
    akaoLoopBranchUsesCurrentRepeatPass();
    akaoTieAfterRestDoesNotExtendPreviousNote();
    akaoTempoFadeEmitsDriverTickRamp();
    akaoPitchSlideAppliesOnceToTheNextNote();
    akaoPortamentoRetainsPitchTransitionIntent();
    akaoRequiredArticulationsComeFromInstrumentRows();
    akaoMelodicRegionsDropAdvancingOverlaps();
    akaoSampleSelectionKeepsPreferredAndRequiredCollections();
    akaoScanPublishesStructuralInstrumentSetAndPreparesBoundView();
    ndsLayoutResolvesNamesFilesAndDependencies();
    ndsLayoutBoundsMalformedTablesAndPointers();
    ndsSequenceFatRangesHandleNormalEmptyAndRecoveredFiles();
    ndsModuleOnlyBuildsDependenciesOfReferencedBanks();
    ndsSequenceDialectDecodesAndRendersNoteWaitCommands();
    ndsSequenceDialectComposesPitchBendRangeActions();
    ndsSequenceDialectEmitsStickyDynamicAdsr();
    ndsSequenceDialectModelsNitroLfoRegisters();
    ndsSynthModulatorsUseSequenceLfoRanges();
    ndsSequenceDialectRevealsRunningSineLfoAtDepthChange();
    ndsSequenceDialectPreservesPortamentoTimingIntent();
    ndsSequenceDialectPreservesTiedSweepVoices();
    ndsSequenceDialectExecutesCallAndReturn();
    ndsSequenceDialectDiscoversSecondaryTrackAddresses();
    ndsSequenceTrackAddressDiscoveryKeepsMalformedBootstrapCommands();
    ndsSequenceDialectAnnotatesModulationDelayOperands();
    ndsSequenceDialectAnnotatesPartialModulationDelayOperands();
    ndsSequenceDialectKeepsEmptyPlaceholderTrack();
    ndsSequenceDialectMarksUnterminatedVarLenAsTruncated();
    ndsSequenceDialectDoesNotLinkInvalidControlTargets();
    ndsMalformedRecoveryKeepsExecutableJumps();
    ndsSynthParserConvertsMaximumReleaseRate();
    ndsSynthParserDerivesAdpcmLengthsSafely();
    ndsWaveArchiveReportsTruncatedSampleHeaders();
    ndsSynthBuilderPreservesSparseWaveIndexesAcrossArchives();
    segSatVlCurveMatchesMm8Saturation();
    segSatCollectionPreparationSuppliesVlTablesToSequence();
    segSatRuntimeMapSelectsBankInsideAnotherSampleSpan();
    segSatMultiBankPlaybackUsesTheActiveBanksVlTable();
    segSatCollectionPreparationReadsVelocityBanksFromSeparateSources();
    segSatSsfExtractorUsesFourByteMiniHeader();
    suzukiPs1DynamicAdsrUsesAuditedDriverCommands();
    suzukiPs1ModuleBuildsFractionallyTunedWdsSynth();
    runWolfTeamSnesModuleTests();
  } catch (const std::exception& ex) {
    std::cerr << ex.what() << '\n';
    return 1;
  }

  return 0;
}
