name: Build
on: 
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  macos:
    name: macOS 13.x+
    runs-on: ${{ (matrix.target == 'intel' && 'macos-15') || 'macos-15' }}
    strategy:
      matrix:
        target: [ "intel", "arm64" ]
    permissions:
      id-token: write
      contents: read
      attestations: write
    env:
      HOMEBREW_PREFIX: ${{ (matrix.target == 'intel' && '/usr/local') || '/opt/homebrew' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
            aqtversion: '==3.1.*'
            version: '6.10.2'
            host: 'mac'
            target: 'desktop'
            arch: 'clang_64'
            modules: 'all'

      - name: "Set environment variables"
        run: |
          echo "BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: "Prepare build"
        run: cmake --preset "macos-${{ matrix.target }}"

      - name: "Build project"
        run: cmake --build --preset "macos-${{ matrix.target }}-release" \
          --target vgmtrans vgmtrans-shell

      - name: "Package DMG (macOS)"
        working-directory: "build/macos-${{ matrix.target }}/"
        run: |
          macdeployqt \
            bin/Release/VGMTrans.app \
            -verbose=3 -always-overwrite -appstore-compliant

      - name: "Checkout create-dmg"
        uses: actions/checkout@v4
        with:
          repository: create-dmg/create-dmg
          path: "./build/macos-${{ matrix.target }}/create-dmg"
          ref: master

      - name: Build macOS DMG
        shell: bash
        working-directory: "build/macos-${{ matrix.target }}/"
        run: |
          ./create-dmg/create-dmg \
            --no-internet-enable \
            --volname "VGMTrans" \
            --volicon "bin/Release/VGMTrans.app/Contents/Resources/appicon.icns" \
            --background "${{ github.workspace }}/bin/dmg/bg.tif" \
            --text-size 12 \
            --window-pos 400 400 \
            --window-size 700 400 \
            --icon-size 80 \
            --icon "VGMTrans.app" 313 97 \
            --hide-extension "VGMTrans.app" \
            --app-drop-link 520 97 \
            --add-file "Unblock & Sign" "${{ github.workspace }}/bin/dmg/selfsign" 313 280 \
            --add-file "README.txt" "${{ github.workspace }}/bin/dmg/README.txt" 520 280 \
            "bin/Release/VGMTrans-${{ github.sha }}.dmg" \
            "bin/Release"
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          subject-name: VGMTrans-${{ github.sha }}-${{ env.BRANCH }}-${{ matrix.target }}-${{ runner.os }}
          subject-path: "build/macos-${{ matrix.target }}/bin/Release/VGMTrans-${{ github.sha }}.dmg"

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: VGMTrans-${{ github.sha }}-${{ env.BRANCH }}-${{ matrix.target }}-${{ runner.os }}.dmg
          path: "build/macos-${{ matrix.target }}/bin/Release/VGMTrans-${{ github.sha }}.dmg"
          
  linux:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.10
      options: --privileged
    name: Linux, x64
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          show-progress: false

      - name: "Set environment variables"
        run: |
          echo "BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: "Build Flatpak"
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: VGMTrans.flatpak
          manifest-path: build-aux/flatpak/io.github.vgmtrans.vgmtrans.yaml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Run linter
        run: |
          flatpak install -y flathub org.flatpak.Builder
          flatpak run --command=flatpak-builder-lint org.flatpak.Builder \
            --gha-format \
            --user-exceptions build-aux/flatpak/flatpak-exceptions.json \
            manifest build-aux/flatpak/io.github.vgmtrans.vgmtrans.yaml
          flatpak run --command=flatpak-builder-lint org.flatpak.Builder \
            --gha-format \
            --exceptions \
            --user-exceptions build-aux/flatpak/flatpak-exceptions.json \
            repo repo
        shell: bash

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          subject-name: VGMTrans-${{ github.sha }}-${{ env.BRANCH }}-x86_64-${{ runner.os }}
          subject-path: "VGMTrans.flatpak"

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: VGMTrans-${{ github.sha }}-${{ env.BRANCH }}-x86_64-${{ runner.os }}.flatpak
          path: VGMTrans.flatpak

  windows:
    runs-on: windows-2022
    strategy:
      matrix:
        target: ['x64', 'x64-clang']
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
       - uses: actions/checkout@v4
         with:
          submodules: recursive
          show-progress: false

       - name: "Source vcvars for ${{ matrix.target }}"
         if: ${{ !contains(matrix.target, '-clang') }}
         uses: ilammy/msvc-dev-cmd@v1
         with:
            arch: ${{ matrix.target != 'x64' && (format('{0}_{1}', 'amd64', matrix.target)) || matrix.target }}

       - name: Install Qt
         uses: jurplel/install-qt-action@v4
         with:
           aqtversion: '==3.1.*'
           version: '6.10.2'
           host: 'windows'
           target: 'desktop'
           arch: 'win64_msvc2022_64'
           modules: 'all'

       - name: "Prepare build"
         run: |
          echo "BRANCH=$(git rev-parse --abbrev-ref HEAD)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PACKAGE_FILE_NAME=VGMTrans-${{ github.sha }}-${{ env.BRANCH }}-${{ matrix.target }}-${{ runner.os }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          # Force to have a flat install package layout.
          # Windows users get frightened at the sight of GNU directories.
          cmake --preset win-${{ matrix.target }} `
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/dist" `
            -DCMAKE_INSTALL_BINDIR="." `
            -DCMAKE_INSTALL_LIBDIR="." `
            -DCPACK_PACKAGE_FILE_NAME="${{ env.PACKAGE_FILE_NAME }}"

       - name: "Build project"
         run: |
           cmake --build `
            --preset win-${{ matrix.target }}-release `
            --target vgmtrans vgmtrans-shell

       - name: "Package project"
         run: |
           cmake --build `
            --preset win-${{ matrix.target }}-release `
            --target package

       - name: Generate artifact attestation
         uses: actions/attest-build-provenance@v3
         if: ${{ github.event_name != 'pull_request' }}
         with:
           subject-path: "build/win-${{ matrix.target }}/${{ env.PACKAGE_FILE_NAME }}.zip"

       - name: "Upload artifact"
         uses: actions/upload-artifact@v4
         with:
           name: ${{ env.PACKAGE_FILE_NAME }}
           path: "build/win-${{ matrix.target }}/${{ env.PACKAGE_FILE_NAME }}.zip"
